services:
  r1:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net12:
        ipv4_address: 10.0.12.5
      net14:
        ipv4_address: 10.0.14.5

  r2:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net12:
        ipv4_address: 10.0.12.2
      net23:
        ipv4_address: 10.0.23.2

  r3:
    build: .
    stdin_open: true
    tty: true
    cap_add:
    - ALL
    privileged: true
    networks:
      net23:
        ipv4_address: 10.0.23.3
      net34:
        ipv4_address: 10.0.34.3

  r4:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net14:
        ipv4_address: 10.0.14.4
      net34:
        ipv4_address: 10.0.34.4

  ha:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net12:
        ipv4_address: 10.0.12.9

  hb:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net34:
        ipv4_address: 10.0.34.9

networks:
  net12:
    ipam:
      driver: default
      config:
        - subnet: 10.0.12.0/24
  net14:
    ipam:
      driver: default
      config:
        - subnet: 10.0.14.0/24
  net23:
    ipam:
      driver: default
      config:
        - subnet: 10.0.23.0/24
  net34:
    ipam:
      driver: default
      config:
        - subnet: 10.0.34.0/24



